modLoader="javafml"
loaderVersion = "[47,)"
license="MIT"

[[mods]]
modId="dtbwg"
version="${file.jarVersion}"
displayName="Dynamic Trees for BWG"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BWG.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-bwg"
logoFile=""
credits=""
authors="Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Oh The Biomes You've Gone
'''

[[dependencies.dtbwg]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtbwg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtbwg]]
modId = "dynamictrees"
mandatory = true
versionRange = "[1.3.0-BETA10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtbwg]]
modId = "dynamictreesplus"
mandatory = false
versionRange = "[1.2.0-BETA2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtbwg]]
modId="biomeswevegone"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
